import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { trpc } from "../utils/api";

export default function Home() {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App + DLC</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid w-full max-w-2xl grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="w-full rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
            </Link>
            <Link
              className="w-full rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
            </Link>
          </div>
          <h2 className="text-3xl font-extrabold tracking-tight text-white sm:text-[4rem]">
            With <span className="text-[hsl(280,100%,70%)]">DLC</span>
          </h2>
          <div className="flex w-full max-w-2xl flex-col gap-2 md:gap-4">
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://clerk.com/"
              target="_blank"
            >
              <Image
                src="/logos/clerk.svg"
                width={32}
                height={32}
                alt="Clerk Logo"
              />
              <h3 className="text-2xl font-bold">Clerk</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://orm.drizzle.team/"
              target="_blank"
            >
              <Image
                src="/logos/drizzle.svg"
                width={32}
                height={32}
                alt="Drizzle ORM Logo"
              />
              <h3 className="text-2xl font-bold">Drizzle ORM</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://jotai.org/"
              target="_blank"
            >
              <span className="h-8 w-8 text-2xl font-bold">👻</span>
              <h3 className="text-2xl font-bold">Jotai</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://lucide.dev/"
              target="_blank"
            >
              <Image
                src="/logos/lucide.svg"
                width={32}
                height={32}
                alt="Lucide Logo"
              />
              <h3 className="text-2xl font-bold">Lucide Icons</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://neon.tech/"
              target="_blank"
            >
              <Image
                src="/logos/neon.svg"
                width={32}
                height={32}
                alt="Neon Logo"
              />
              <h3 className="text-2xl font-bold">Neon</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://playwright.dev/"
              target="_blank"
            >
              <Image
                src="/logos/playwright.svg"
                width={32}
                height={32}
                alt="Playwright Logo"
              />
              <h3 className="text-2xl font-bold">Playwright</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
            <Link
              className="flex w-full items-center gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://turbo.build/"
              target="_blank"
            >
              <Image
                src="/logos/turbo.png"
                width={32}
                height={32}
                alt="Turbo Repo Logo"
              />
              <h3 className="text-2xl font-bold">TurboRepo</h3>
              <span className="ml-auto text-2xl font-bold">→</span>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        </div>
      </main>
    </>
  );
}
